
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: regionalpd-storageclass
parameters:
  fstype: ext4
  replication-type: regional-pd
  type: pd-ssd
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - australia-southeast1-a
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - australia-southeast1-b